# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='this_job',
            name='job_type',
        ),
    ]
