# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_this_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='this_job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
