# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20171118_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='this_job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
