# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelancer',
            field=models.BooleanField(default=True),
        ),
    ]
