# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171117_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
