# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171117_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='superuser',
        ),
    ]
