# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171120_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileemp',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilefree',
            name='user_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
