# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171125_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileemp',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='profilefree',
            name='user_name',
        ),
    ]
