# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171203_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefree',
            old_name='website',
            new_name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='profilefree',
            name='company',
        ),
    ]
