# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20171204_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefree',
            old_name='Portfolio',
            new_name='portfolio',
        ),
    ]
