# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('short_text', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=50)),
            ],
        ),
    ]
