# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20171013_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
