# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20171013_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
