# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
