# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
