# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_auto_20171118_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_text', models.TextField()),
                ('bid_time', models.CharField(max_length=50)),
                ('bid_budget', models.CharField(max_length=50)),
                ('bid_posted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bid_poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='employee.This_Job')),
            ],
        ),
    ]
